# Language (en, ja)
language: en
# Upload settings
upload:
  # Enable upload functionality
  enabled: true
  # Discord Webhook URL for uploads
  webhook-url: https://discord.com/api/webhooks/xxxxxxxxxxxxxxxxxx/xxxxxxxxxxxxxxxxxxxxxxxxxxxx-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
# Download settings
download:
  # Enable download functionality
  enabled: true
  # Maximum size of downloaded files (in bytes) (-1 for unlimited)
  max-size: 8388608 # 8MB
  # Download source restriction settings
  url-restriction:
    # Enable download source restriction
    enabled: false
    # Prefix for URL restrictions (Note: For Discord attachment URLs, make sure it starts with cdn. and ends with /)
    # Usually, you just need to replace the xxxxxxxxxxxxxxxxxx part with your own channel ID
    prefix: https://cdn.discordapp.com/attachments/xxxxxxxxxxxxxxxxxx/
    # The name of the download location (displayed in the error message)
    # This name is used in error messages when downloading from locations other than the specified prefix.
    # If set to #schem-storage, the error message will display as "You can only download schematic files from the '#schem-storage' channel within Discord"
    name: "#schem-storage"
file:
  # Path to the schematics folder
  folder-path: plugins/WorldEdit/schematics