name: SchemUploader
version: '${project.version}'
main: com.kamesuta.schemuploader.SchemUploader
api-version: 1.16
authors: [ Kamesuta ]

permissions:
  schemuploader.upload:
    description: Permission to upload schematics
    default: true
  schemuploader.download:
    description: Permission to download schematics
    default: true

commands:
  schem_upload:
    description: Upload a schematic
    usage: /schem_upload <schem_name> [message]
    permission: schemuploader.upload
  schem_download:
    description: Download a schematic
    usage: /schem_download <schem_name> <schem_file_url> [-f]
    permission: schemuploader.download